name: "Chore: PR title & releasing"
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr-title:
    name: Assert PR title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: assert conventional commit message
        id: lint
        uses: amannn/action-semantic-pull-request@v5
        with:
          # subject must start with uppercase letter and may not end with a dot/space
          subjectPattern: ^[A-Z].+[^. ]$
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Post comment about invalid PR title
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: conventional-commit-pr-title
          message: |
            Thank you for your contribution!

            This repository requires pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            <details><summary><b>Details:</b></summary>

            ```
            ${{ steps.lint.outputs.error_message }}
            ```

            </details>
      - name: Delete comment about invalid PR title
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: conventional-commit-pr-title
          delete: true

  release-drafter:
    name: ${{ github.event_name == 'pull_request' && 'Add labels' || 'Create draft release' }}
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event_name == 'pull_request' && 'Assign labels' || 'Update release draft' }}
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: ${{ github.event_name == 'pull_request' }}
          disable-autolabeler: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
